name: CI/CD Learning Staging

on:
  push:
    branches:
      - stagging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.DEPLOY_HOST}}
        username: ${{secrets.DEPLOY_STAGING_USER}}
        password: ${{secrets.STAGING_DEPLOY_PASSWORD}}
        port: ${{secrets.DEPLOY_PORT}}
        key: ${{secrets.SSH_PRIVATE_KEY}}
        passphrase: ${{secrets.DEPLOY_PASSPHRASE}}
        script: |
          cd test
          git stash
          git checkout stagging
          git pull origin stagging
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          nvm use 18
          npm i
          pm2 restart app-stagging-start.json --time --watch false
